### ISSUE TITLE
Training deterministic model

### ISSUE THREAD

**Issue by JiajianLu** [Majiker/STAR#14] opened 2021-07-12 06:12 UTC
Hi can i ask how to train the deterministic model? Should I just feed the temporal input embedding without concatenating gaussian noise into the output layer? Thank you!

**Comment by cunjunyu** [comment] 2021-07-12 06:36
Thanks for your interest in the work.

> Should I just feed the temporal input embedding without concatenating gaussian noise into the output layer?

Generally yes. However, this repo is built to reproduce the result of the stochastic version, which is the main result. Since I have left SenseTime, I cannot access the original code of the deterministic version.  You may need to modify the details of the code and tune the hyperparameters by yourself for the deterministic version.  
 
Thanks.

**Comment by JiajianLu** [comment] 2021-07-12 06:53
Thank you for your quick reply. I'll try it out. Here is another question, for the stochastic model, how should I find the best prediction among all the sampled predictions when the ground truth is unknown?

**Comment by cunjunyu** [comment] 2021-07-12 07:00
I assume you are referring to the test phase. 

In that case, you simply cannot evaluate your model this way unless the evaluation algorithm accepts multiple predictions. Or, you may utilize a certain sampling method to sample the trajectory with the highest possibility. For example, one very simple strategy is to use the mean of the distribution predicted.

**Comment by JiajianLu** [comment] 2021-07-12 07:40
Got it. In that case the mean of the distribution would be 0 since we are training with standard gaussian?

**Comment by cunjunyu** [comment] 2021-07-12 13:10
Nope, only the noise is the standard guassian. You may take the mean of the prediction.

**Comment by cunjunyu** [comment] 2021-07-17 10:14
I will close the issue for now, please feel free to reopen it if you have any further questions.

**Closed as completed by cunjunyu** 2021-07-17 10:14 UTC

**Comment by ycl204432** [comment] 2021-07-29 13:50
Hello, I would like to ask how to train a deterministic model. I tried to simply round off the random noise, but the training result is not correct.
